export default [
   { value: 'Roboto', label: 'Roboto' }, 
   { value: 'OpenSans', label: 'Open Sans' }, 
   { value: 'Spectral', label: 'Spectral' }, 
   { value: 'Slabo27px', label: 'Slabo 27px' }, 
   { value: 'Lato', label: 'Lato' }, 
   { value: 'RobotoCondensed', label: 'Roboto Condensed' }, 
   { value: 'Oswald', label: 'Oswald' }, 
   { value: 'SourceSansPro', label: 'Source Sans Pro' }, 
   { value: 'Raleway', label: 'Raleway' }, 
   { value: 'Montserrat', label: 'Montserrat' }, 
   { value: 'PTSans', label: 'PT Sans' }, 
   { value: 'RobotoSlab', label: 'Roboto Slab' }, 
   { value: 'Merriweather', label: 'Merriweather' }, 
   { value: 'SairaCondensed', label: 'Saira Condensed' }, 
   { value: 'Saira', label: 'Saira' }, 
   { value: 'SairaSemiCondensed', label: 'Saira Semi Condensed' }, 
   { value: 'SairaExtraCondensed', label: 'Saira Extra Condensed' }, 
   { value: 'Archivo', label: 'Archivo' }, 
   { value: 'Ubuntu', label: 'Ubuntu' }, 
   { value: 'Lora', label: 'Lora' }, 
   { value: 'Manuale', label: 'Manuale' }, 
   { value: 'AsapCondensed', label: 'Asap Condensed' }, 
   { value: 'Faustina', label: 'Faustina' }, 
   { value: 'Cairo', label: 'Cairo' }, 
   { value: 'PlayfairDisplay', label: 'Playfair Display' }, 
   { value: 'DroidSerif', label: 'Droid Serif' }, 
   { value: 'NotoSans', label: 'Noto Sans' }, 
   { value: 'PTSerif', label: 'PT Serif' }, 
   { value: 'DroidSans', label: 'Droid Sans' }, 
   { value: 'Arimo', label: 'Arimo' }, 
   { value: 'Poppins', label: 'Poppins' }, 
   { value: 'TitilliumWeb', label: 'Titillium Web' }, 
   { value: 'Muli', label: 'Muli' }, 
   { value: 'IndieFlower', label: 'Indie Flower' }, 
   { value: 'Mada', label: 'Mada' }, 
   { value: 'PTSansNarrow', label: 'PT Sans Narrow' }, 
   { value: 'NotoSerif', label: 'Noto Serif' }, 
   { value: 'Bitter', label: 'Bitter' }, 
   { value: 'Dosis', label: 'Dosis' }, 
   { value: 'JosefinSans', label: 'Josefin Sans' }, 
   { value: 'Inconsolata', label: 'Inconsolata' }, 
   { value: 'Arvo', label: 'Arvo' }, 
   { value: 'Hind', label: 'Hind' }, 
   { value: 'Cabin', label: 'Cabin' }, 
   { value: 'Oxygen', label: 'Oxygen' }, 
   { value: 'Acme', label: 'Acme' }, 
   { value: 'ArchivoNarrow', label: 'Archivo Narrow' }, 
   { value: 'MuktaVaani', label: 'Mukta Vaani' }, 
   { value: 'Play', label: 'Play' }, 
   { value: 'Cuprum', label: 'Cuprum' }, 
   { value: 'MavenPro', label: 'Maven Pro' }, 
   { value: 'EBGaramond', label: 'EB Garamond' }, 
   { value: 'PassionOne', label: 'Passion One' }, 
   { value: 'RopaSans', label: 'Ropa Sans' }, 
   { value: 'ArchivoBlack', label: 'Archivo Black' }, 
   { value: 'PathwayGothicOne', label: 'Pathway Gothic One' }, 
   { value: 'Exo', label: 'Exo' }, 
   { value: 'LibreFranklin', label: 'Libre Franklin' }, 
   { value: 'CreteRound', label: 'Crete Round' }, 
   { value: 'PTSansCaption', label: 'PT Sans Caption' }, 
   { value: 'SourceCodePro', label: 'Source Code Pro' }
]